version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=_eth0_
    volumes:
      - ./es-data:/home/serji/elastic/data
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch1:9200/
      ELASTICSEARCH_HOST: http://elasticsearch1:9200/
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/:/home/serji/elastic/kibana/config:ro
    networks:
      - elastic
  apmserver:
    image: docker.elastic.co/apm/apm-server:7.9.1
    container_name: apm-server
    command: --strict.perms=false

    ports:
      - 8200:8200
      - 8201:8200
    environment:
      - apm-server.host=0.0.0.0
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - apm-server.rum.enabled=true
      - setup.kibana.host="kibana:5601"
      - setup.template.enabled=true
    # volumes:
    #   - ${PWD}/configs/apm-server.yml:/usr/share/apm-server/apm-server.yml
    networks:
        - elastic
volumes:
  es-data:
    driver: local
  logs:
    driver: local

networks:
  elastic:
    driver: bridge
